[tool.ruff]
line-length = 88
exclude = [
    "tests/*",  # Exclude test files or directories
    "docs/*",  # Exclude documentation files or directories
]


[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes errors
    "W",  # pycodestyle warnings
    "C90",  # custom rules (e.g., PEP8 compliance)
    "I",  # import rules (similar to isort)
    "A",  # additional rules for even stricter linting
]
ignore = []

[tool.ruff.lint.per-file-ignores]
"src/backend/data/migrations/*.py" = ["E501"]

[tool.pytest.ini_options]
pythonpath = ". src"
DJANGO_SETTINGS_MODULE = "src.backend.settings"
python_files = "test_*.py"